version: "3"

services:
  pinot-zookeeper:
    image: apachepinot/pinot:release-0.10.0
    hostname: pinot-zookeeper
    container_name: "pinot-client-rust-pinot-zookeeper"
    ports:
      - "2181:2181"
    command: StartZookeeper

  pinot-controller:
    image: apachepinot/pinot:release-0.10.0
    hostname: pinot-controller
    container_name: "pinot-client-rust-pinot-controller"
    volumes:
      - ./db:/db
    ports:
      - "9000:9000"
    command: StartController -zkAddress pinot-zookeeper:2181
    depends_on:
      - pinot-zookeeper
  
  pinot-broker:
    image: apachepinot/pinot:release-0.10.0
    hostname: pinot-broker
    container_name: "pinot-client-rust-pinot-broker"
    volumes:
      - ./db:/db
    ports:
      - "8099:8099"
    command: StartBroker -zkAddress pinot-zookeeper:2181
    restart: unless-stopped
    depends_on:
      - pinot-zookeeper
      - pinot-controller
  
  pinot-server:
    image: apachepinot/pinot:release-0.10.0
    hostname: pinot-server
    container_name: "pinot-client-rust-pinot-server"
    volumes:
      - ./db:/db
    ports:
      - "8098:8098"
    command: StartServer -zkAddress pinot-zookeeper:2181
    depends_on:
      - pinot-zookeeper
      - pinot-controller

# cargo will try to redownload packages @ docker-compose up so store them here.
volumes:
  pgdata: {}
